site_name: Tapioca-Wrapper
pages:
- Home: index.md
- About: about.md
- Quickstart: quickstart.md
- Availble Flavours: flavours.md
- New Flavour: newflavour.md
- Contributors: contributors.md
theme: readthedocs
